apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cvmfs-gxy-main-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cvmfs-gxy-main
