apiVersion: v1
kind: Pod
metadata:
  name: csicvmfs-demo-pod
spec:
  containers:
   - name: csicvmfs-demo
     image: busybox
     imagePullPolicy: IfNotPresent
     command: [ "/bin/sh", "-c", "trap : TERM INT; (while true; do sleep 1000; done) & wait" ]
     volumeMounts:
       - name: mypvc
         mountPath: /data.galaxyproject.org
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: csi-cvmfs-pvc
