[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "v1.0.0"

[[constraint]]
  version = "v1.0.2"
  name = "github.com/kubernetes-csi/drivers"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[override]]
  revision = "v2.7.1"
  name = "github.com/docker/distribution"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.18.0"

[[override]]
  version = "kubernetes-1.13.3"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.13.3"

[[override]]
  version = "kubernetes-1.13.3"
  name = "k8s.io/api"

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
