# Default values for galaxy-cvmfs-csi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: cvmfs

# All contents will be run through tpl
# All mountPaths are relative to /etc/cvmfs/
configs:
  defaultLocal:
    mountPath: default.local
    contents: |
      CVMFS_SERVER_URL="http://cvmfs1-iu0.galaxyproject.org/cvmfs/@fqrn@;http://cvmfs1-tacc0.galaxyproject.org/cvmfs/@fqrn@;http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@;http://galaxy.jrc.ec.europa.eu:8008/cvmfs/@fqrn@;http://cvmfs1-ufr0.galaxyproject.eu/cvmfs/@fqrn@"
      CVMFS_KEYS_DIR="/etc/cvmfs/keys/"
      CVMFS_USE_GEOAPI=yes
      CVMFS_HTTP_PROXY="DIRECT"
      # It is advised to change these configs in the cache section of the helm values
      CVMFS_QUOTA_LIMIT={{ .Values.cache.size }}
      CVMFS_CACHE_BASE={{ .Values.cache.mountPath }}
  gxyDataKey:
    mountPath: keys/data.galaxyproject.org.pub
    contents: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5LHQuKWzcX5iBbCGsXGt
      6CRi9+a9cKZG4UlX/lJukEJ+3dSxVDWJs88PSdLk+E25494oU56hB8YeVq+W8AQE
      3LWx2K2ruRjEAI2o8sRgs/IbafjZ7cBuERzqj3Tn5qUIBFoKUMWMSIiWTQe2Sfnj
      GzfDoswr5TTk7aH/FIXUjLnLGGCOzPtUC244IhHARzu86bWYxQJUw0/kZl5wVGcH
      maSgr39h1xPst0Vx1keJ95AH0wqxPbCcyBGtF1L6HQlLidmoIDqcCQpLsGJJEoOs
      NVNhhcb66OJHah5ppI1N3cZehdaKyr1XcF9eedwLFTvuiwTn6qMmttT/tHX7rcxT
      owIDAQAB
      -----END PUBLIC KEY-----
  gxyMainKey:
    mountPath: keys/main.galaxyproject.org.pub
    contents: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6S6Tugcv4kk4C06f574l
      YCXQdK6lv2m7mqCh60G0zL1+rAkkEBDWna0yMQLBbj+yDsHjcOe0yISzbTfzG6wk
      KnHZUQ/JOeK7lUAbDMxHqnjkEPAbAl4vXl2Y04MW2lzJtXcDKakmLirvV/dfUYqE
      gGGx0dc/Z+XmUTf1DvZFJknrBUUxO5+F6m7k/NGrlpAca+e9B0kwCclaE4NyaNWK
      Jv5rPWCYz5/sDNW4cNvBdBjwGf46etbczmJoTAbl0oM6LLGdebwkJStd0R1wkj+A
      torRYcoFZICTZqY9e/KsadHUeZnH3RvfMypH5oS1POzsFszoSxBhZIBkZbG3/f9Y
      OQIDAQAB
      -----END PUBLIC KEY-----
cache:
  storageClassName: manual
  accessMode: ReadWriteMany
  # size in Mi, will propagate to both default.local and PV/PVC size
  size: 10000
  hostPath: /tmp/k8s/volumes/cvmfs/cache
  mountPath: /mnt/cvmfs/cache
# Advanced settings
# Changing these settings is not advised unless you know what you are doing
csiPlugin:
  image: gitlab-registry.nautilus.optiputer.net/prp/cvmfs-csi:latest
  args:
    - "--nodeid=$(NODE_ID)"
    - "--endpoint=$(CSI_ENDPOINT)"
    - "--v=5"
    - "--drivername=csi-cvmfsplugin"
  pluginDirectory: /var/lib/kubelet/plugins/csi-cvmfsplugin
  nodeDriverImage: quay.io/k8scsi/csi-node-driver-registrar:v1.0.2
csiAttacher:
  image: quay.io/k8scsi/csi-attacher:v1.0.1
  args:
    - "--v=5"
    - "--csi-address=$(ADDRESS)"
csiProvisioner:
  image: quay.io/k8scsi/csi-provisioner:v1.0.1
  args:
    - "--provisioner=csi-cvmfsplugin"
    - "--csi-address=$(ADDRESS)"
    - "--v=5"
