kind: PersistentVolume
apiVersion: v1
metadata:
  name: cvmfs-cache
  namespace: {{ .Values.namespace }}
  labels:
    app: csi-cvmfsplugin
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.cache.pv.size | quote }}
  accessModes:
    - ReadWriteMany
  hostPath:
    # This is a host specific path where Galaxy files will be placed.
    path: "/tmp/k8s/volumes/cvmfs/cache"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cvmfs-cache
  namespace: {{ .Values.namespace }}
  labels:
    app: csi-cvmfsplugin
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.cache.storageClass }}
  {{- if (eq "-" .Values.cache.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.cache.storageClass }}"
  {{- end }}
  {{- end }}
  accessModes:
    - {{ .Values.cache.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.cache.pv.size | quote }}
