kind: Service
apiVersion: v1
metadata:
  name: csi-cvmfsplugin-provisioner
  namespace: {{ .Values.namespace }}
  labels:
    app: csi-cvmfsplugin-provisioner
spec:
  selector:
    app: csi-cvmfsplugin-provisioner
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-cvmfsplugin-provisioner
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "csi-cvmfsplugin-provisioner"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-cvmfsplugin-provisioner
    spec:
      serviceAccount: cvmfs-provisioner
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.0.1
          args:
            - "--provisioner=csi-cvmfsplugin"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: {{ .Values.cvmfsPlugin.pluginDirectory }}/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: {{ .Values.cvmfsPlugin.pluginDirectory }}
      volumes:
        - name: socket-dir
          hostPath:
            path: {{ .Values.cvmfsPlugin.pluginDirectory }}
            type: DirectoryOrCreate
