apiVersion: v1
kind: ServiceAccount
metadata:
  name: cvmfs-attacher
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cvmfs-external-attacher-runner
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cvmfs-attacher-role
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: cvmfs-attacher
roleRef:
  kind: ClusterRole
  name: cvmfs-external-attacher-runner
  apiGroup: rbac.authorization.k8s.io
