kind: Service
apiVersion: v1
metadata:
  name: csi-cvmfsplugin-provisioner
  namespace: cvmfs
  labels:
    app: csi-cvmfsplugin-provisioner
spec:
  selector:
    app: csi-cvmfsplugin-provisioner
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-cvmfsplugin-provisioner
  namespace: cvmfs
spec:
  serviceName: "csi-cvmfsplugin-provisioner"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-cvmfsplugin-provisioner
    spec:
      serviceAccount: cvmfs-provisioner
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v0.3.0
          args:
            - "--provisioner=csi-cvmfsplugin"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi-cvmfsplugin/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/csi-cvmfsplugin
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-cvmfsplugin
            type: DirectoryOrCreate
