kind: Service
apiVersion: v1
metadata:
  name: csi-cvmfsplugin-attacher
  namespace: cvmfs
  labels:
    app: csi-cvmfsplugin-attacher
spec:
  selector:
    app: csi-cvmfsplugin-attacher
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-cvmfsplugin-attacher
  namespace: cvmfs
spec:
  serviceName: "csi-cvmfsplugin-attacher"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-cvmfsplugin-attacher
    spec:
      serviceAccount: cvmfs-attacher
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.0.1
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi-cvmfsplugin/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/csi-cvmfsplugin
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-cvmfsplugin
            type: DirectoryOrCreate
