apiVersion: v1
kind: ServiceAccount
metadata:
  name: cvmfs-attacher
  namespace: cvmfs

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cvmfs-external-attacher-runner
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cvmfs-attacher-role
  namespace: cvmfs
subjects:
  - kind: ServiceAccount
    name: cvmfs-attacher
    namespace: cvmfs
roleRef:
  kind: ClusterRole
  name: cvmfs-external-attacher-runner
  apiGroup: rbac.authorization.k8s.io