apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: cvmfs
  name: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.cvmfs.svc.cluster.local
    path: "/"
