kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cvmfs-psp
subjects:
  - kind: ServiceAccount
    name: cvmfs-nodeplugin
    namespace: cvmfs
  - kind: ServiceAccount
    name: cvmfs-attacher
    namespace: cvmfs
  - kind: ServiceAccount
    name: cvmfs-provisioner
    namespace: cvmfs
roleRef:
  kind: ClusterRole
  name: psp:privileged-user
  apiGroup: rbac.authorization.k8s.io